### ISSUE TITLE
Breaks in Cipher Encryption and Decryption Logic

### ISSUE THREAD

**Issue by churr0** [churr0/Evolutionary-Enigma#2]
It has been observed that some input messages and settings are being incorrectly encrypted and decrypted in such a way that causes the encrypted/decrypted value of the a letter to essentially be out of scope (i.e. letters are being encrypted/decrypted to non-alpha characters such as ']' and '/'). This problem is causing an error when the encryption/decryption function attempts to find the certain character in a list containing all upper-case alpha characters (i.e. "rotorI"). There does not seem to be a common letter or index within the input message associated with the issue, most likely due to the nature of Enigma's dynamic algorithm.

Traceback (within encryption function):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "enigma.py", line 265, in encrypt
    index = current_rotorIII.index(subIII)
ValueError: '\\' is not in list
```

**Comment by churr0** [comment]
Encryption solved: https://github.com/churr0/Evolutionary-Enigma/commit/4a41f4ffa686d916b950f6a0c571f8d4a8e64918#diff-b0da275520918e23dd615e2a747528f1

**Comment by churr0** [comment]
Decryption solved: https://github.com/churr0/Evolutionary-Enigma/commit/58368dee45351c1cd02fe068a22786fb5e33500a#diff-43cd3eef9fd7622dc56ccae5733f8b3f
