### ISSUE TITLE
Decryption breaks inside Docker container

### ISSUE THREAD

**Issue by churr0** [churr0/Evolutionary-Enigma#3]
Decryption logic seems to break inside of the Docker container, while it runs with no issues locally. Error message shows that a specified value cannot be found within the rotor/alphabet list.

Error Example:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "enigma.py", line 402, in decrypt
    index = current_rotorIII.index(subIII)
ValueError: ']' is not in list
```

**Comment by churr0** [comment]
Issue fixed by adding additional error handling and checks around indices: https://github.com/churr0/Evolutionary-Enigma/commit/fb92765dbb191abaae9821c7b88d977e3d7dfc11#diff-43cd3eef9fd7622dc56ccae5733f8b3f
